# action.yml — Beargrease GitHub Action

name: "Beargrease Test Runner"
description: "A transparent, Docker-driven Solana test validator harness for Anchor programs."
author: "Richard G. Melvin, Cabrillo! Labs"
branding:
  icon: "box"
  color: "blue"

inputs:
  wallet-secret:
    description: "Private key (JSON array) of test wallet, stored in GitHub Secrets"
    required: true
  test-runner:
    description: "Specify which test strategy to use: anchor | yarn"
    required: false
    default: "auto"

runs:
  using: "composite"
  steps:
    - name: 💾 Write wallet file from secret
      shell: bash
      run: |
        mkdir -p .ledger/wallets
        echo "${{ inputs.wallet-secret }}" > .ledger/wallets/test-user.json

    - name: ⛓️ Install Solana CLI (via Anza)
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: 🧪 Run Beargrease test harness
      shell: bash
      run: |
        TEST_RUNNER="${{ inputs.test-runner }}" "${{ github.action_path }}/scripts/run-tests.sh"