name: Beargrease
description: Solana Docker test harness
author: rgmelvin

inputs:
  test-runner:
    description: "Which test runner to use: auto, anchor, or yarn"
    required: false
    default: "auto"

runs:
  using: "composite"
  steps:
    - name: 🧾 Checkout project
      uses: actions/checkout@v4

    - name: 🧰 Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: 🦀 Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: 🪝 Install jq (if missing)
      run: |
        if ! command -v jq &>/dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi
      shell: bash

    - name: ⛓️ Install Anchor (with libudev-dev)
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev
        cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v0.31.1 --force
      shell: bash

    - name: 🐻 Run Beargrease test harness
      working-directory: ${{ github.action_path }}
      run: |
        TEST_RUNNER="${{ inputs.test-runner }}" \
        BEARGREASE_WALLET_SECRET="${{ env.BEARGREASE_WALLET_SECRET }}" \
        ./scripts/run-tests.sh
      shell: bash