# action.yml — Beargrease GitHub Action

name: "Beargrease Test Runner"
description: "A transparent, Docker-driven Solana test validator harness for Anchor programs."
author: "Richard G. Melvin, Cabrillo! Labs"
branding:
  icon: "box"
  color: "blue"

inputs:
  wallet-secret:
    description: "Base64-encoded private key (JSON array) of test wallet, stored in GitHub Secrets"
    required: true
  test-runner:
    description: "Specify which test strategy to use: anchor | yarn"
    required: false
    default: "auto"

runs:
  using: "composite"
  steps:
    - name: 💾 Decode base64 wallet and write to file
      shell: bash
      run: |
        mkdir -p .ledger/wallets
        printf '%s' "${{ inputs.wallet-secret }}" | base64 -d > .ledger/wallets/test-user.json

    - name: 🐛 Debug wallet file contents
      shell: bash
      run: |
        echo "===== .ledger/wallets/test-user.json ====="
        cat .ledger/wallets/test-user.json
        echo "=========================================="

    - name: 🧪 Dump wallet file hex and byte count
      shell: bash
      run: |
        echo "===== Hex dump of wallet file ====="
        xxd .ledger/wallets/test-user.json
        echo "===== Byte count ====="
        wc -c .ledger/wallets/test-user.json
        echo "==================================="


    - name: ⛓️ Install Solana CLI (via Anza)
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: 🧪 Run Beargrease test harness
      shell: bash
      run: |
        TEST_RUNNER="${{ inputs.test-runner }}" "${{ github.action_path }}/scripts/run-tests.sh"