name: 🧪 Beargrease Self-Test CI

on:
  push:
    branches:
      - ci-dev
  pull_request:

env:
  ANCHOR_VERSION: "0.31.1"
  SOLANA_VERSION: "1.18.11"
  NODE_VERSION: "20.18.0"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🧰 Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: 💾 Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: 💾 Cache Cargo git repos
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      - name: ⚓ Install Solana CLI (Anza recommended)
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: 🚀 Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v${ANCHOR_VERSION} anchor-cli --locked
          anchor --version

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🔨 Buiuld Anchor program
        run: anchor build

      - name: 🚀 Deploy program
        run: anchor deploy

      - name: 🪪 Extract deployed program ID
        id: extract-program-id
        run: |
          PROGRAM_ID=$(solana address -k target/deploy/beargrease-keypair.json)
          echo "program_id=$PROGRAM_ID" >> $GITHUB_OUTPUT

      - name: 🧵 Patch Anchor.toml and lib.rs with deployed program ID
        run: |
          PROGRAM_ID="${{ steps.extract-program-id.outputs.program_id }}"
          echo "📛 Program ID is $PROGRAM_ID"

          # Patch Anchor.toml
          sed -i "s/beargrease *= *\".*\"/beargrease = \"$PROGRAM_ID\"/" Anchor.toml

          # Patch lib.rs (optional but often necessary)
          sed -i "s/declare_id!(\".*\")/declare_id!(\"PROGRAM_ID\")/" programs/beargrease/src/lib.rs

      - name: 🔁 Rebuild and redeploy with patched program ID
        run: |
          anchor build
          anchor deploy